[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "phcl"
version = "0.1.0"
description = "Python-powered HCL DSL: write Terraform resources using clean Python classes"
authors = [
    {name = "Dmitry Sergeev",email = "realnexusway@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.setuptools]
packages = ["phcl"]

[project.scripts]
phcl = "phcl.cli.phcl:main"
