[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "phcl"
version = "0.3.2"
description = "Python-powered structural DSL for authoring native HCL2."
authors = [
    {name = "Dmitry Sergeev",email = "realnexusway@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[project.optional-dependencies]
terraform = [
    "phcl-terraform>=0.1.4",
]

[dependency-groups]
dev = [
    "pytest>=8.0",
]

[tool.setuptools.packages.find]
include = ["phcl*"]
namespaces = true

[project.scripts]
phcl = "phcl.cli.phcl:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["--import-mode=importlib"]
